include::common/theme.adoc[]
= Managed Runtime Systems =

include::common/settings.adoc[]
include::common/license.adoc[]

== The JVM architecture ==
[ditaa, target=jvm-architecture, format=svg, transparent=false, scale=2, separation=false]
----
+--------+        +---------+
|{d}cFC0 |        |{d}cFC0  |       +--------------+
|        | javac  |         | java  |cB50          |
| .java  +------->| .class  +------>| Class Loader |
|        |        |         |       |              |
|        |        |         |       +-------+------+
+--------+        +---------+               ^
                                            |
Data Locations                              V
/-----------------------------------------------------------------------\
| +-------------+-----------+------------+-------------+--------------+ |
| | cDDD        | cDDD      | cDDD       | cDDD        | cDDD         | |
| | Method Area | Heap Area | Stack Area | PC register | Native Stack | |
| |             |           |            |             |              | |
| +-------------+-----------+------------+-------------+--------------+ |
\-----------------------------------------------------------------------/
         ^                          ^
         |                          |
         V                          V
+------------------+   +--------------------------+   +------------------+
| cB50             |   | cDDD                     |   | cDDD             |
| Execution Engine |<->| Native Methods Interface |<->| Native Libraries |
|                  |   |                          |   |                  |
+------------------+   +--------------------------+   +------------------+
----


=== Class loading ===
* Verification
* Preparation of JVM internal data structures
* Resolution of references (might load other classes)
* Initialization

[.notes]
--
* Loading: A class is obtained from a file and loaded to the JVM memory.
* Verifying: Check whether or not the read class is configured as described in the Java Language Specification and JVM specifications. This is the most complicated test process of the class load processes, and takes the longest time. Most cases of the JVM TCK test cases are to test whether or not a verification error occurs by loading wrong classes.
* Preparing: Prepare a data structure that assigns the memory required by classes and indicates the fields, methods, and interfaces defined in the class.
* Resolving: Change all symbolic references in the constant pool of the class to direct references.
* Initializing: Initialize the class variables to proper values. Execute the static initializers and initialize the static fields to the configured values.
--

=== Java Class file ===
[source,c]
----
ClassFile {
  u4             magic;
  u2             minor_version;
  u2             major_version;
  u2             constant_pool_count;
  cp_info        constant_pool[constant_pool_count-1];
  u2             access_flags;
  u2             this_class;
  u2             super_class;
  u2             interfaces_count;
  u2             interfaces[interfaces_count];
  u2             fields_count;
  field_info     fields[fields_count];
  u2             methods_count;
  method_info    methods[methods_count];
  u2             attributes_count;
  attribute_info attributes[attributes_count];
}
----


=== Field Info ===
[source,c]
----
field_info {
  u2 access_flags; // public, private, protected, static, final,
                   // volatile, transient, synthetic, enum
  u2 name_index;
  u2 descriptor_index;
  u2 attributes_count;
  attribute_info attributes[attributes_count]; // e.g., Deprecated
}
----


=== Java fields ===
* Reference (Size is implementation-dependent)
* Primitive
** 8, 16, 32, or 64-bit Integer (`byte`, `short`, `int`, `long`, `boolean`, `char`)
** 32 or 64-bit IEEE 754 floating-point (`float`, `double`)

[.xx-small]
=== Field Descriptors ===

[.xx-small]
[options="header", cols="2,1,2", frame=none, grid=none]
|====
| Abbreviation| Type| Example

| B| byte|
| C| char|
| D| double|
| F| float|
| I| int|
| J| long|
| `L<ClassName>;`| reference| `Ljava/lang/String;`
| S| short|
| Z| boolean|
| [| array| `[I`   `[[[D`    `[Ljava/lang/Object;`
|====


=== Method Info ===
[source,c]
----
method_info {
  u2 access_flags; // public, private, native, var args, synthetic ...
  u2 name_index;
  u2 descriptor_index;
  u2 attributes_count;
  attribute_info attributes[attributes_count]; // e.g., Code, Exceptions
}
----

Method Descriptors:
....
  void foo(int a, Object o) => (ILjava/lang/Object;)V
  String bar(int[][] i)     => ([[I)Ljava/lang/String;
....


=== Code attribute ===
[source,c]
----
Code_attribute {
  u2 attribute_name_index;
  u4 attribute_length;
  u2 max_stack;
  u2 max_locals;
  u4 code_length;
  u1 code[code_length]; // The actual bytecode
  u2 exception_table_length;
  { u2 start_pc; // if catch_type is thrown between start_pc and end_pc,
    u2 end_pc;   // execute handler at handler_pc
    u2 handler_pc;
    u2 catch_type;
  } exception_table[exception_table_length];
  u2 attributes_count;
  attribute_info attributes[attributes_count]; // line numbers, stack maps,...
}
----


== Runtime ==

=== Java Stack vs Native Stack ===
[ditaa, target=java-native-stack, format=svg, transparent=true, separation=false]
----
                      /------------------\
                      |cFC0              |
                      |      Frame       |
+-------------+       |                  |
|             |       |        ^         |
| Java Stack  |       |        |         |
|             |       |        |         |
|      ^      |       + ---------------- +
|      |      |       |  operand stack 2 |
|      |      |       + ---------------- +
| +---------+ |       |  operand stack 1 |
| |         | |       + ---------------- +
| | frame 2 | |       |  operand stack 0 |
| |         | |       + ---------------- +
| +---------+ |       |local variable n  |
| |cFC0     | |       + ---------------- +
| | frame 1 | |       |        .         |
| |         | |       |        .         |
| +---------+ |       |        .         |
| |         | |       + ---------------- +
| | frame 0 | |       |local variable 1  |
| |         | |       + ---------------- +
+-+---------+-+       |local variable 0  |
                      + ---------------- +
                      |  return address  |
                      \------------------/
----

=== Java Threads ===
* A Program Counter
** Class
** Method
** Bytecode-offset or native code pointer
* A Java Stack
* Native stack


=== Java Objects and Arrays ===
[ditaa, target=object-array-layout, format=svg, scale=2, transparent=true, separation=false]
----
+---------+         +-----------+
| cBLU    |         | cBLU      |
|  header |         |   header  |
|         |         |           |
+---------+         +-----------+
| field 0 |         |  length   |
+---------+         +-----------+
| field 1 |         | element 0 |
+---------+         +-----------+
|    .    |         | element 1 |
|    .    |         +-----------+
|    .    |         |     .     |
+---------+         |     .     |
| field n |         |     .     |
+---------+         +-----------+
                    | element n |
                    +-----------+
----


=== More ===
https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html[The Java Virtual Machine Specification, Java SE 11 Edition, Chapter 4]
